[template.environment]
  AUTHOR_NAME = "Garud"
  AUTHOR_EMAIL = "celestialentity@duck.com"
  SITE_TITLE = "CelestialEntity"
  SITE_DESCRIPTION = "Website description"
  GITHUB_TOKEN = "Access token from Github with 'repo' permissions"

[[plugins]]
package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
  buildEvent = "onBuild"

[functions]
  directory = "functions"

[[redirects]]
  from = "/11ndieweb/:function"
  to = "/.netlify/functions/11ndieweb"
  status = 200