[template.environment]
  AUTHOR_NAME = "Garud"
  AUTHOR_EMAIL = "celestialentity@duck.com"
  SITE_TITLE = "CelestialEntity"
  SITE_DESCRIPTION = "A peronal Garden."
  GITHUB_TOKEN = "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"

[[plugins]]
package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
  buildEvent = "onBuild"

[functions]
  directory = "functions"

[[redirects]]
  from = "/11ndieweb/:function"
  to = "/.netlify/functions/11ndieweb"
  status = 200